### PR TITLE
Style the Views exposed filter and bulk operations forms

### PR DESCRIPTION
**Pull request by mortenson**
This PR implements the concept from #18 to style the Views bulk operations and exposed filter forms.

### CODE REVIEW

**Comment by briancwald** [comment]
This is what it is looking like for me. I think something in the CSS may have gotten messed up from recent pushes I've made maybe? Have you tried against head?

Also, I noticed if I select a item, then deselect it still says '1 item selected'.

screenshot 2017-07-20 07 17 34

**Comment by briancwald** [comment]
Loooking good! I see there are some merge conflicts with master because I have done a number of CSS/JS and SASS file cleanup we will need to resolve but the filters work great.

2 notes:

- let's make the filter button flat, not jumping out.
- I wonder if we can add the selected item's header to 'sticky-header' so s if you are on a page with long content you always see the actions visible. This basically is why core has 2 "submit" buttons on the page, which was a less useful attempt at dealign with that.

**Comment by briancwald** [comment]
I think its up to date now.

**Comment by mortenson** [comment]
I should have noted this in the first comment but the filter chips are also not implemented - do you want those added in this PR?

**Comment by mortenson** [comment]
@briancwald There were some remaining merge conflicts that broke styling of the bulk action ellipsis button, which should be fixed now.

For (1), I can't find a reference in http://materializecss.com/buttons.html or in the Material Design styleguide for a flat round (on hover) icon button. I'm also wondering if users would have a hard time knowing that they can click it if it was flat.

I'll work on (2), making the bulk operations header sticky.

**Comment by briancwald** [comment]
Yeah, so I'm thinking about it. Lets make that button a square, and then we can address the applied filters by just simply adding a 'badge' to the button when a filter is applied.

**Pull request merged**
